server:
  port: 8080

spring:
  application:
    name: ms-vidasalud-bff
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID:9333d7eb-2af5-4631-835e-78e32d2ae6d1}/v2.0
          audiences: ${AZURE_API_CLIENT_ID:api://471213b2-94cc-4f45-bc30-d084984ac045}

appointments:
  url: ${APPOINTMENTS_URL:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.security: DEBUG

